# Generated by Django 3.0.3 on 2020-02-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип владельца',
                'verbose_name_plural': 'Типы владельцев',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=None, max_length=64)),
                ('full_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('flat', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('people', models.IntegerField(null=True)),
                ('car', models.BooleanField(default=False)),
                ('car_model', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('car_color', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('owner_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.OwnerType')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Все пользователи',
            },
        ),
    ]
