# Generated by Django 2.2 on 2020-03-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=64, verbose_name='Тип владельца')),
            ],
            options={
                'verbose_name': 'Тип владельца',
                'verbose_name_plural': 'Типы владельцев',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Ф.И.О.')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('flat', models.IntegerField(null=True, verbose_name='Номер квартиры')),
                ('floor', models.IntegerField(null=True, verbose_name='Этаж')),
                ('people', models.IntegerField(null=True, verbose_name='Кол-во жителей')),
                ('owner_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to='users.OwnerType', verbose_name='Тип владельца')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Все пользователи',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=64, verbose_name='Бренд')),
                ('car_model', models.CharField(max_length=64, verbose_name='Модель')),
                ('car_number', models.CharField(max_length=64, verbose_name='Номер')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automobile', to='users.User', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
