# Generated by Django 2.2 on 2020-03-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='housereg.House', verbose_name='Адрес'),
        ),
    ]
