# Generated by Django 3.0.3 on 2020-02-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200224_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownertype',
            old_name='type',
            new_name='user_type',
        ),
    ]
