# Generated by Django 3.0.3 on 2020-02-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200226_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_model',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=64)),
                ('car_model', models.CharField(max_length=64)),
                ('car_number', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='automobile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Car'),
        ),
    ]
