# Generated by Django 3.0.3 on 2020-02-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200227_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='automobile',
        ),
    ]
