# Generated by Django 3.0.3 on 2020-03-10 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20200228_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=64, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=64, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=64, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automobile', to='users.User', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='ownertype',
            name='user_type',
            field=models.CharField(max_length=64, verbose_name='Тип владельца'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flat',
            field=models.IntegerField(null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owner_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to='users.OwnerType', verbose_name='Тип владельца'),
        ),
        migrations.AlterField(
            model_name='user',
            name='people',
            field=models.IntegerField(null=True, verbose_name='Кол-во жителей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Телефон'),
        ),
    ]
