# Generated by Django 3.0.3 on 2020-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_field',
            field=models.CharField(max_length=250),
        ),
    ]
