# Generated by Django 3.0.3 on 2020-02-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20200224_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
