# Generated by Django 3.0.3 on 2020-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_auto_20200310_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='password'),
        ),
    ]
