# Generated by Django 3.0.3 on 2020-02-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('RE', 'Ремонт'), ('TE', 'Пропуск'), ('SE', 'Доп Услуга')], max_length=20)),
                ('status', models.CharField(choices=[('IN', 'В процессе'), ('RD', 'Выполнено')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_field', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Service')),
            ],
        ),
    ]
