# Generated by Django 3.0.3 on 2020-02-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200226_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='service',
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ManyToManyField(related_name='comment', to='service.Service'),
        ),
    ]
