# Generated by Django 3.0.3 on 2020-02-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200226_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='service',
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='service.Service'),
            preserve_default=False,
        ),
    ]
