# Generated by Django 3.0.3 on 2020-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200226_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
