# Generated by Django 3.0.3 on 2020-02-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200226_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
