# Generated by Django 3.0.3 on 2020-03-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housereg', '0002_auto_20200226_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinhouse',
            name='count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='usersinhouse',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
