# Generated by Django 3.0.3 on 2020-03-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housereg', '0003_auto_20200306_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='people',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='usersinhouse',
            old_name='count',
            new_name='people',
        ),
    ]
