# Generated by Django 3.0.3 on 2020-03-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housereg', '0004_auto_20200306_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='count',
            new_name='people',
        ),
    ]
