# Generated by Django 3.0.3 on 2020-03-10 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housereg', '0006_auto_20200306_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.CharField(max_length=16, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='people',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во жителей'),
        ),
        migrations.AlterField(
            model_name='usersinhouse',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='housereg.House', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='usersinhouse',
            name='people',
            field=models.IntegerField(default=None, verbose_name='Кол-во жителей'),
        ),
        migrations.AlterField(
            model_name='usersinhouse',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Житель'),
        ),
    ]
